services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: congthanh2k4/tool_lab-node
    container_name: tool_lab_app
    ports:
      - "3000:3000"
    restart: unless-stopped
